<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<Import Project="../../Nu/Nu.targets" />

	<ItemGroup>
		<None Include="Assets\*" />
		<None Include="Assets\*\*" />
		<Compile Include="Core\Assets.fs" />
		<Compile Include="Core\Constants.fs" />
		<Compile Include="Core\Simulants.fs" />
		<Compile Include="Core\Advents.fs" />
		<Compile Include="Core\Inventory.fs" />
		<Compile Include="Core\RandMap.fs" />
		<Compile Include="Core\Data.fs" />
		<Compile Include="Core\Algorithms.fs" />
		<Compile Include="Core\Events.fs" />
		<Compile Include="Effects\EffectAspects.fs" />
		<Compile Include="Effects\EffectDescriptors.fs" />
		<Compile Include="Title\Title.fs" />
		<Compile Include="Credits\Credits.fs" />
		<Compile Include="RingMenu\RingMenu.fs" />
		<Compile Include="Reticles\Reticles.fs" />
		<Compile Include="Character\CharacterAnimationState.fs" />
		<Compile Include="Character\CharacterInputState.fs" />
		<Compile Include="Character\CharacterState.fs" />
		<Compile Include="Character\Character.fs" />
		<Compile Include="Character\CharacterPlus.fs" />
		<Compile Include="Character\CharacterDispatcher.fs" />
		<Compile Include="Battle\Dialog.fs" />
		<Compile Include="Battle\DialogContent.fs" />
		<Compile Include="Battle\Battle.fs" />
		<Compile Include="Battle\BattleDispatcher.fs" />
		<Compile Include="SpiritOrb\Chest.fs" />
		<Compile Include="SpiritOrb\Portal.fs" />
		<Compile Include="SpiritOrb\Narrative.fs" />
		<Compile Include="SpiritOrb\Spirit.fs" />
		<Compile Include="SpiritOrb\SpiritOrb.fs" />
		<Compile Include="SpiritOrb\SpiritOrbDispatcher.fs" />
		<Compile Include="Prop\Prop.fs" />
		<Compile Include="Prop\PropPlus.fs" />
		<Compile Include="Prop\PropDispatcher.fs" />
		<Compile Include="Avatar\Avatar.fs" />
		<Compile Include="Avatar\AvatarDispatcher.fs" />
		<Compile Include="Teammate\Teammate.fs" />
		<Compile Include="Teammate\TeammateDispatcher.fs" />
		<Compile Include="Field\Menu.fs" />
		<Compile Include="Field\PartyMenu.fs" />
		<Compile Include="Field\Shop.fs" />
		<Compile Include="Field\Field.fs" />
		<Compile Include="Field\FieldContent.fs" />
		<Compile Include="Field\FieldDispatcher.fs" />
		<Compile Include="OmniBlade\OmniBlade.fs" />
		<Compile Include="OmniBlade\OmniBladePlugin.fs" />
		<Compile Include="Program.fs" />
		<Content Include="AssetGraph.nuag">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Overlayer.nuol">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<None Include="App.config" />
	</ItemGroup>

</Project>