// Nu Game Engine.
// Required Notice:
// Copyright (C) Bryan Edds.
// Nu Game Engine is licensed under the Nu Game Engine Noncommercial License.
// See https://github.com/bryanedds/Nu/blob/master/License.md.

#r "nuget: Prime"
#r "nuget: ppy.SDL3-CS"

open System
open System.IO
open System.Text.RegularExpressions
open Prime
open SDL

// this function was copied and converted from - https://stackoverflow.com/a/46095771
let upperCaseToPascalCase (original : string) =
    let invalidCharsRgx = Regex "[^_a-zA-Z0-9]"
    let whiteSpace = Regex "(?<=\\s)"
    let startsWithLowerCaseChar = Regex "^[a-z]"
    let firstCharFollowedByUpperCasesOnly = Regex "(?<=[A-Z])[A-Z0-9]+$"
    let lowerCaseNextToNumber = Regex "(?<=[0-9])[a-z]"
    let upperCaseInside = Regex "(?<=[A-Z])[A-Z]+?((?=[A-Z][a-z])|(?=[0-9]))"
    let pascalCase =
        // replace white spaces with undescore, then replace all invalid chars with empty string
        invalidCharsRgx.Replace(whiteSpace.Replace(original, "_"), "")
        // split by underscores
        |> fun str -> str.Split ([|'_'|], StringSplitOptions.RemoveEmptyEntries)
        // set first letter to uppercase
        |> Array.map (fun w -> startsWithLowerCaseChar.Replace (w, _.Value.ToUpperInvariant()))
        // replace second and all following upper case letters to lower if there is no next lower (ABC -> Abc)
        |> Array.map (fun w -> firstCharFollowedByUpperCasesOnly.Replace (w, _.Value.ToLowerInvariant()))
        // set upper case the first lower case following a number (Ab9cd -> Ab9Cd)
        |> Array.map (fun w -> lowerCaseNextToNumber.Replace (w, _.Value.ToUpperInvariant()))
        // lower second and next upper case letters except the last if it follows by any lower (ABcDEf -> AbcDef)
        |> Array.map (fun w -> upperCaseInside.Replace (w, _.Value.ToLowerInvariant()))
    String.Concat pascalCase

let generateBindingsCode codesStr =
    "// Nu Game Engine.\n" +
    "// Required Notice:\n" +
    "// Copyright (C) Bryan Edds.\n" +
    "// Nu Game Engine is licensed under the Nu Game Engine Noncommercial License.\n" +
    "// See https://github.com/bryanedds/Nu/blob/master/License.md.\n" +
    "\n" +
    "//*********************************************************************************************//\n" +
    "//                                                                                             //\n" +
    "// NOTE: This code is GENERATED by 'Scripts/GenerateInputBindings.fsx' as this is a one-to-one //\n" +
    "// correspondence to SDL3.SDL_Scancode with cleaner names. Do NOT edit this code by hand!      //\n" +
    "//                                                                                             //\n" +
    "//*********************************************************************************************//\n" +
    "\n" +
    "namespace Nu\n" +
    "open System\n" +
    "\n" +
    "/// Denotes a key on the keyboard.\n" +
    "type KeyboardKey =\n" +
    codesStr

let code =
    Enum.GetValues<SDL_Scancode> ()
    |> Array.filter (function SDL_Scancode.SDL_SCANCODE_COUNT | SDL_Scancode.SDL_SCANCODE_RESERVED -> false | _ -> true)
    |> Array.map (fun value ->
        let name =
            match value with
            | SDL_Scancode.SDL_SCANCODE_0 -> "Num0"
            | SDL_Scancode.SDL_SCANCODE_1 -> "Num1"
            | SDL_Scancode.SDL_SCANCODE_2 -> "Num2"
            | SDL_Scancode.SDL_SCANCODE_3 -> "Num3"
            | SDL_Scancode.SDL_SCANCODE_4 -> "Num4"
            | SDL_Scancode.SDL_SCANCODE_5 -> "Num5"
            | SDL_Scancode.SDL_SCANCODE_6 -> "Num6"
            | SDL_Scancode.SDL_SCANCODE_7 -> "Num7"
            | SDL_Scancode.SDL_SCANCODE_8 -> "Num8"
            | SDL_Scancode.SDL_SCANCODE_9 -> "Num9"
            | SDL_Scancode.SDL_SCANCODE_RETURN -> "Enter" // NOTE: ImGui calls this the 'enter' key, so I choose that.
            | SDL_Scancode.SDL_SCANCODE_RETURN2 -> "Enter2"
            | SDL_Scancode.SDL_SCANCODE_NONUSHASH -> "NonUsHash"
            | SDL_Scancode.SDL_SCANCODE_NONUSBACKSLASH -> "NonUsBackslash"
            | _ ->
                let name = (string value).Replace ("SDL_SCANCODE_", "")
                let name = Regex.Replace (name, "LEFT|RIGHT|UP|DOWN|LOCK|SCREEN|GUI|SHIFT|CTRL|ALT|BRACE|BRACKET|PAREN|SEL|SEPARATOR|MINUS|UNIT|REQ", "_$0")
                let name = Regex.Replace (name, "MEM|EQUALS|END|DBL|VERTICAL|CURRENCY|CLEAR|ALT|LOCK", "$0_")
                upperCaseToPascalCase name
        "    | " + name + " = " + string (int value))
    |> String.concat "\n"
    |> generateBindingsCode
File.WriteAllText (__SOURCE_DIRECTORY__ + "/../Sdl/SdlInputBindings.fs", code)