// IMPORTANT!
// NOTE: this MUST be run in the 64-bit FSI (In VS, Tools -> Options... -> F# Tools -> 64-bit F# Interactive [set to true]).
// IMPORTANT!

// IMPORTANT!
// NOTE: change these paths to make this script run with your Nu installation.
// IMPORTANT!
#r "C:/OmniBlade/Prime/xUnit/xunit.dll"
#r "C:/OmniBlade/Prime/FSharpx.Core/FSharpx.Core.dll"
#r "C:/OmniBlade/Prime/Prime/Prime/bin/Release/Prime.exe"
#r "C:/OmniBlade/Aml/Aml/Aml/bin/Optimized/Aml.exe"
#r "C:/OmniBlade/Nu/xUnit/xunit.dll"
#r "C:/OmniBlade/Nu/FSharpx.Core/FSharpx.Core.dll"
#r "C:/OmniBlade/Nu/Farseer/FarseerPhysics.dll"
#r "C:/OmniBlade/Nu/SDL2#/Release/SDL2#.dll"
#r "C:/OmniBlade/Nu/TiledSharp/Release/TiledSharp.dll"
System.IO.Directory.SetCurrentDirectory "C:/OmniBlade/Nu/Nu/Nu/bin/Release"

#load "Core.fs"
#load "RQueue.fs"
#load "Constants.fs"
#load "Math.fs"
#load "Voords.fs"
#load "Assets.fs"
#load "Physics.fs"
#load "Audio.fs"
#load "Rendering.fs"
#load "Metadata.fs"
#load "Input.fs"
#load "Camera.fs"
#load "DomainModel.fs"
#load "Entities.fs"
#load "Groups.fs"
#load "Screens.fs"
#load "Games.fs"
#load "Sdl.fs"
#load "Sim.fs"
#load "OmniBlade.fs"

open System
open SDL2
open OpenTK
open TiledSharp
open Nu
open Nu.Core
open Nu.Constants
open Nu.Math
open Nu.Voords
open Nu.Assets
open Nu.Physics
open Nu.Audio
open Nu.Rendering
open Nu.Metadata
open Nu.CameraModule
open Nu.DomainModel
open Nu.Entities
open Nu.Groups
open Nu.Screens
open Nu.Games
open Nu.Sdl
open Nu.WorldModule
open Nu.OmniBlade