// Nu Game Engine.
// Copyright (C) Bryan Edds, 2013-2015.

namespace Nu
open System
open OpenTK
open Prime
open Nu

[<RequireQualifiedAccess>]
module Events =

    let Any = ntoa<obj> !!"*"
    let Update = ntoa<unit> !!"Update"
    let Select = ntoa<unit> !!"Select"
    let Deselect = ntoa<unit> !!"Deselect"
    let Down = ntoa<unit> !!"Down"
    let Up = ntoa<unit> !!"Up"
    let Click = ntoa<unit> !!"Click"
    let On = ntoa<unit> !!"On"
    let Off = ntoa<unit> !!"Off"
    let Touch = ntoa<Vector2> !!"Touch"
    let Untouch = ntoa<Vector2> !!"Untouch"
    let Mouse = ntoa<obj> !!"Mouse"
    let MouseMove = Mouse -<- ntoa<MouseMoveData> !!"Move"
    let MouseDrag = Mouse -<- ntoa<MouseMoveData> !!"Drag"
    let MouseLeft = Mouse -<- ntoa<MouseButtonData> !!"Left"
    let MouseCenter = Mouse -<- ntoa<MouseButtonData> !!"Center"
    let MouseRight = Mouse -<- ntoa<MouseButtonData> !!"Right"
    let MouseX1 = Mouse -<- ntoa<MouseButtonData> !!"X1"
    let MouseX2 = Mouse -<- ntoa<MouseButtonData> !!"X2"
    let MouseLeftDown = MouseLeft -|- ntoa !!"Down"
    let MouseLeftUp = MouseLeft -|- ntoa !!"Up"
    let MouseLeftChange = MouseLeft -|- ntoa !!"Change"
    let MouseCenterDown = MouseCenter -|- ntoa !!"Down"
    let MouseCenterUp = MouseCenter -|- ntoa !!"Up"
    let MouseCenterChange = MouseCenter -|- ntoa !!"Change"
    let MouseRightDown = MouseRight -|- ntoa !!"Down"
    let MouseRightUp = MouseRight -|- ntoa !!"Up"
    let MouseRightChange = MouseRight -|- ntoa !!"Change"
    let MouseX1Down = MouseX1 -|- ntoa !!"Down"
    let MouseX1Up = MouseX1 -|- ntoa !!"Up"
    let MouseX1Change = MouseX1 -|- ntoa !!"Change"
    let MouseX2Down = MouseX2 -|- ntoa !!"Down"
    let MouseX2Up = MouseX2 -|- ntoa !!"Up"
    let MouseX2Change = MouseX2 -|- ntoa !!"Change"
    let KeyboardKey = ntoa<obj> !!"KeyboardKey"
    let KeyboardKeyDown = Mouse -<- ntoa<KeyboardKeyData> !!"Down"
    let KeyboardKeyUp = Mouse -<- ntoa<KeyboardKeyData> !!"Up"
    let KeyboardKeyChange = Mouse -<- ntoa<KeyboardKeyData> !!"Change"
    let Collision = ntoa<CollisionData> !!"Collision"
    let Incoming = ntoa<unit> !!"Incoming"
    let IncomingStart = Incoming -|- ntoa !!"Start"
    let IncomingFinish = Incoming -|- ntoa !!"Finish"
    let Outgoing = ntoa<unit> !!"Outgoing"
    let OutgoingStart = Outgoing -|- ntoa !!"Start"
    let OutgoingFinish = Outgoing -|- ntoa !!"Finish"
    let WorldState = ntoa<obj> !!"WorldState"
    let WorldStateChange = WorldState -<- ntoa<WorldStateChangeData> !!"Change"
    let Game = ntoa<obj> !!"Game"
    let GameChange = Game -<- ntoa<Game SimulantChangeData> !!"Change"
    let Screen = ntoa<obj> !!"Screen"
    let ScreenAdd = Screen -<- ntoa<unit> !!"Add"
    let ScreenRemoving = Screen -<- ntoa<unit> !!"Removing"
    let ScreenChange = Screen -<- ntoa<Screen SimulantChangeData> !!"Change"
    let Group = ntoa<obj> !!"Group"
    let GroupAdd = Group -<- ntoa<unit> !!"Add"
    let GroupRemoving = Group -<- ntoa<unit> !!"Removing"
    let GroupChange = Group -<- ntoa<Group SimulantChangeData> !!"Change"
    let Entity = ntoa<obj> !!"Entity"
    let EntityAdd = Entity -<- ntoa<unit> !!"Add"
    let EntityRemoving = Entity -<- ntoa<unit> !!"Removing"
    let EntityChange = Entity -<- ntoa<Entity SimulantChangeData> !!"Change"