@echo off
@echo Installing NuGame project template for Visual Studio 2013...
copy NuGame.zip "%userprofile%\Documents\Visual Studio 2013\Templates\ProjectTemplates"
@echo Installing NuGame project template for Visual Studio 2012...
copy NuGame.zip "%userprofile%\Documents\Visual Studio 2012\Templates\ProjectTemplates"
pause
