// Nu Game Engine.
// Copyright (C) Bryan Edds, 2013-2020.

#I __SOURCE_DIRECTORY__
#load "Interactive.fsx"
open System
open System.Text.RegularExpressions
open System.Linq
open System.IO
open Prime
open Nu
open SDL2

// this function was stolen and converted from - https://stackoverflow.com/a/46095771
let upperCaseToPascalCase (original : string) =
    let invalidCharsRgx = Regex "[^_a-zA-Z0-9]"
    let whiteSpace = Regex "(?<=\\s)"
    let startsWithLowerCaseChar = Regex "^[a-z]"
    let firstCharFollowedByUpperCasesOnly = Regex "(?<=[A-Z])[A-Z0-9]+$"
    let lowerCaseNextToNumber = Regex "(?<=[0-9])[a-z]"
    let upperCaseInside = Regex "(?<=[A-Z])[A-Z]+?((?=[A-Z][a-z])|(?=[0-9]))"
    let pascalCase =
        // replace white spaces with undescore, then replace all invalid chars with empty string
        invalidCharsRgx.Replace(whiteSpace.Replace(original, "_"), "") |>
        // split by underscores
        (fun (str : string) -> str.Split ([|'_'|], StringSplitOptions.RemoveEmptyEntries)) |>
        // set first letter to uppercase
        (fun (strs : string array) -> strs.Select(fun w -> startsWithLowerCaseChar.Replace (w, fun m -> m.Value.ToUpper ()))) |>
        // replace second and all following upper case letters to lower if there is no next lower (ABC -> Abc)
        (fun (strs : string seq) -> strs.Select (fun w -> firstCharFollowedByUpperCasesOnly.Replace(w, fun m -> m.Value.ToLower ()))) |>
        // set upper case the first lower case following a number (Ab9cd -> Ab9Cd)
        (fun (strs : string seq) -> strs.Select(fun w -> lowerCaseNextToNumber.Replace(w, fun m -> m.Value.ToUpper ()))) |>
        // lower second and next upper case letters except the last if it follows by any lower (ABcDEf -> AbcDef)
        (fun (strs : string seq) -> strs.Select(fun w -> upperCaseInside.Replace(w, fun m -> m.Value.ToLower ())))
    String.Concat pascalCase

let enumEntries (ty : Type) =
    ty.GetEnumNames () |>
    enumerable<string> |>
    Seq.map (fun (name : string) ->
        let name = name.Replace ("SDL_SCANCODE_", "")
        let firstChar = name.[0] // NOTE: elided bounds check because I presume no case where this is possible
        if firstChar >= '0' && firstChar <= '9'
        then "Num" + name
        else name) |>
    flip Seq.zip (ty.GetEnumValues () |> enumerable<int>) |>
    Seq.filter (fun (name, _) -> name <> "SDL_NUM_SCANCODES") |>
    Seq.map (mapFst upperCaseToPascalCase) |>
    List.ofSeq

let enumEntryToCode (entryName : string, entryValue : int) =
    "    | " + entryName + " = " + scstring entryValue

let enumEntriesToCode entries =
    let codes = List.map enumEntryToCode entries
    String.Join ("\n", codes)

let generateBindingsCode codesStr =
    "// Nu Game Engine.\n" +
    "// Copyright (C) Bryan Edds, 2013-2020.\n" +
    "\n" +
    "//*********************************************************************************************//\n" +
    "//                                                                                             //\n" +
    "// NOTE: This code is GENERATED by 'GenerateInputBindings.fsx'! Do NOT edit this code by hand! //\n" +
    "//                                                                                             //\n" +
    "//*********************************************************************************************//\n" +
    "\n" +
    "namespace Nu\n" +
    "open System\n" +
    "open Prime\n" +
    "open Nu\n" +
    "open SDL2\n" +
    "\n" +
    "type KeyboardKey =\n" +
    codesStr +
    "\n"

do
    typeof<SDL.SDL_Scancode> |>
    enumEntries |>
    enumEntriesToCode |>
    generateBindingsCode |>
    fun code -> File.WriteAllText ("../../InputBindings.fs", code)