// Nu Game Engine.
// Copyright (C) Bryan Edds, 2013-2020.

//*********************************************************************************************//
//                                                                                             //
// NOTE: This code is GENERATED by 'GenerateWorldBindings.fsx'! Do NOT edit this code by hand! //
//                                                                                             //
//*********************************************************************************************//

namespace Nu
open System
open System.Numerics
open Prime
open Nu

[<RequireQualifiedAccess>]
module WorldBindings =

    let [<Literal>] BindingKeywords =
        ""

    let tryGetBinding fnName =
        match WorldScripting.Bindings.TryGetValue fnName with
        | (true, binding) -> Some binding
        | (false, _) -> None

    let initBindings () =
        let bindings =
            [
            ] |>
            dictPlus StringComparer.Ordinal
        WorldScripting.Bindings <- bindings
