// Nu Game Engine.
// Copyright (C) Bryan Edds, 2013-2023.

namespace OmniBlade
open System
open Prime
open Nu

[<RequireQualifiedAccess>]
module Assets =

    [<RequireQualifiedAccess>]
    module Global =

        let SaveFilePath1 = "OmniBlade1.sav"
        let SaveFilePath2 = "OmniBlade2.sav"
        let SaveFilePath3 = "OmniBlade3.sav"

    [<RequireQualifiedAccess>]
    module Data =

        let WeaponDataFilePath = "Assets/Data/WeaponData.csv"
        let ArmorDataFilePath = "Assets/Data/ArmorData.csv"
        let AccessoryDataFilePath = "Assets/Data/AccessoryData.csv"
        let ConsumableDataFilePath = "Assets/Data/ConsumableData.csv"
        let TechDataFilePath = "Assets/Data/TechData.csv"
        let ArchetypeDataFilePath = "Assets/Data/ArchetypeData.csv"
        let CharacterDataFilePath = "Assets/Data/CharacterData.csv"
        let ShopDataFilePath = "Assets/Data/ShopData.csv"
        let FieldDataFilePath = "Assets/Data/FieldData.csv"
        let BattleDataFilePath = "Assets/Data/BattleData.csv"
        let EncounterDataFilePath = "Assets/Data/EncounterData.csv"
        let TechAnimationDataFilePath = "Assets/Data/TechAnimationData.csv"
        let CharacterAnimationDataFilePath = "Assets/Data/CharacterAnimationData.csv"

    [<RequireQualifiedAccess>]
    module Gui =

        let PackageName = "Gui"
        let Font = asset<Font> PackageName "Font" // TODO: see if this is openly licensed (manaspace font).
        let NuSlide = asset<Image> PackageName "NuSlide"
        let HeaderImage = asset<Image> PackageName "Header"
        let DialogShortImage = asset<Image> PackageName "DialogShort"
        let DialogThinImage = asset<Image> PackageName "DialogThin"
        let DialogThickImage = asset<Image> PackageName "DialogThick"
        let DialogFatImage = asset<Image> PackageName "DialogFat"
        let DialogXLImage = asset<Image> PackageName "DialogXL"
        let DialogXXLImage = asset<Image> PackageName "DialogXXL"
        let ButtonSmallUpImage = asset<Image> PackageName "ButtonSmallUp"
        let ButtonSmallDownImage = asset<Image> PackageName "ButtonSmallDown"
        let ButtonUpImage = asset<Image> PackageName "ButtonUp"
        let ButtonDownImage = asset<Image> PackageName "ButtonDown"
        let ButtonBigUpImage = asset<Image> PackageName "ButtonBigUp"
        let ButtonBigDownImage = asset<Image> PackageName "ButtonBigDown"
        let ButtonLongUpImage = asset<Image> PackageName "ButtonLongUp"
        let ButtonLongDownImage = asset<Image> PackageName "ButtonLongDown"
        let ButtonSquishedUpImage = asset<Image> PackageName "ButtonSquishedUp"
        let ButtonSquishedDownImage = asset<Image> PackageName "ButtonSquishedDown"
        let ButtonShortUpImage = asset<Image> PackageName "ButtonShortUp"
        let ButtonShortDownImage = asset<Image> PackageName "ButtonShortDown"
        let HealthBorderImage = asset<Image> PackageName "HealthBorder"
        let TechBorderImage = asset<Image> PackageName "TechBorder"
        let AffirmSound = asset<Sound> PackageName "Affirm"
        let MistakeSound = asset<Sound> PackageName "Mistake"
        let SlotSound = asset<Sound> PackageName "Slot"
        let TitleSong = { FadeInTime = 0L; FadeOutTime = Constants.Audio.FadeOutTimeDefault; StartTime = 0L; Volume = Constants.Audio.SongVolumeDefault; Song = asset<Song> PackageName "Title" }
        let CreditsSong = { FadeInTime = 0L; FadeOutTime = Constants.Audio.FadeOutTimeDefault; StartTime = 0L; Volume = Constants.Audio.SongVolumeDefault; Song = asset<Song> PackageName "Credits" }
        let IntroSong = { FadeInTime = 0L; FadeOutTime = 90L; StartTime = 0L; Volume = Constants.Audio.SongVolumeDefault; Song = asset<Song> PackageName "Intro" }
        let TitleGroupFilePath = "Assets/Gui/Groups/Title.nugroup"
        let PickGroupFilePath = "Assets/Gui/Groups/Pick.nugroup"
        let IntroGroupFilePath = "Assets/Gui/Groups/Intro.nugroup"
        let Intro2GroupFilePath = "Assets/Gui/Groups/Intro2.nugroup"
        let Intro3GroupFilePath = "Assets/Gui/Groups/Intro3.nugroup"
        let Intro4GroupFilePath = "Assets/Gui/Groups/Intro4.nugroup"
        let Intro5GroupFilePath = "Assets/Gui/Groups/Intro5.nugroup"

    [<RequireQualifiedAccess>]
    module Field =

        let PackageName = "Field"
        let WoodenChestOpenedImage = asset<Image> PackageName "WoodenChestOpened"
        let WoodenChestClosedImage = asset<Image> PackageName "WoodenChestClosed"
        let SteelChestOpenedImage = asset<Image> PackageName "SteelChestOpened"
        let SteelChestClosedImage = asset<Image> PackageName "SteelChestClosed"
        let BrassChestOpenedImage = asset<Image> PackageName "BrassChestOpened"
        let BrassChestClosedImage = asset<Image> PackageName "BrassChestClosed"
        let WoodenDoorOpenedImage = asset<Image> PackageName "WoodenDoorOpened"
        let WoodenDoorClosedImage = asset<Image> PackageName "WoodenDoorClosed"
        let SteelDoorOpenedImage = asset<Image> PackageName "SteelDoorOpened"
        let SteelDoorClosedImage = asset<Image> PackageName "SteelDoorClosed"
        let OldDoorOpenedImage = asset<Image> PackageName "OldDoorOpened"
        let OldDoorClosedImage = asset<Image> PackageName "OldDoorClosed"
        let BarredDoorOpenedImage = asset<Image> PackageName "BarredDoorOpened"
        let BarredDoorClosedImage = asset<Image> PackageName "BarredDoorClosed"
        let ThrowSwitchOffImage = asset<Image> PackageName "ThrowSwitchOff"
        let ThrowSwitchOnImage = asset<Image> PackageName "ThrowSwitchOn"
        let StepPlateImage = asset<Image> PackageName "StepPlate"
        let SavePointImage = asset<Image> PackageName "SavePoint"
        let StairsImage = asset<Image> PackageName "Stairs"
        let FlameImage = asset<Image> PackageName "Flame"
        let SpiritImage = asset<Image> PackageName "Spirit"
        let SpiritChestClosedImage = asset<Image> PackageName "SpiritChestClosed"
        let SpiritChestOpenedImage = asset<Image> PackageName "SpiritChestOpened"
        let SpiritPortalImage = asset<Image> PackageName "SpiritPortal"
        let SpiritNarrativeImage = asset<Image> PackageName "SpiritNarrative"
        let SpiritAvatarImage = asset<Image> PackageName "SpiritAvatar"
        let SpiritOrbImage = asset<Image> PackageName "SpiritOrb"
        let WarpAnimationSheet = asset<Image> PackageName "Warp"
        let WindAnimationSheet = asset<Image> PackageName "Wind"
        let SealAnimationSheet = asset<Image> PackageName "Seal"
        let NpcAnimationSheet = asset<Image> PackageName "Npcs"
        let BossAnimationSheet = asset<Image> PackageName "Bosses"
        let ShopkeepAnimationSheet = asset<Image> PackageName "Shopkeep"
        let JinnAnimationSheet = asset<Image> PackageName "Jinn"
        let ShadeAnimationSheet = asset<Image> PackageName "Shade"
        let MaelAnimationSheet = asset<Image> PackageName "Mael"
        let RiainAnimationSheet = asset<Image> PackageName "Riain"
        let PericAnimationSheet = asset<Image> PackageName "Peric"
        let JinnPortraitImage = asset<Image> PackageName "JinnPortrait"
        let ShadePortraitImage = asset<Image> PackageName "ShadePortrait"
        let MaelPortraitImage = asset<Image> PackageName "MaelPortrait"
        let RiainPortraitImage = asset<Image> PackageName "RiainPortrait"
        let PericPortraitImage = asset<Image> PackageName "PericPortrait"
        let StepStairSound = asset<Sound> PackageName "StepStair"
        let StepPlateSound = asset<Sound> PackageName "StepPlate"
        let StepSaveSound = asset<Sound> PackageName "StepSave"
        let StepWarpSound = asset<Sound> PackageName "StepWarp"
        let BeastGrowlSound = asset<Sound> PackageName "BeastGrowl"
        let BeastDeathSound = asset<Sound> PackageName "BeastDeath"
        let HealSound = asset<Sound> PackageName "Heal"
        let CureSound = asset<Sound> PackageName "Cure"
        let SilkSound = asset<Sound> PackageName "Silk"
        let PurchaseSound = asset<Sound> PackageName "Purchase"
        let DoorOpenSound = asset<Sound> PackageName "DoorOpen"
        let DoorLockedSound = asset<Sound> PackageName "DoorLocked"
        let ChestOpenSound = asset<Sound> PackageName "ChestOpen"
        let ChestLockedSound = asset<Sound> PackageName "ChestLocked"
        let SwitchUseSound = asset<Sound> PackageName "SwitchUse"
        let SwitchStuckSound = asset<Sound> PackageName "SwitchStuck"
        let SealedSound = asset<Sound> PackageName "Sealed"
        let WhooshSound = asset<Sound> PackageName "Whoosh"
        let UnsheatheSound = asset<Sound> PackageName "Unsheathe"
        let GrowthSound = asset<Sound> PackageName "Growth"
        let HitSound = asset<Sound> PackageName "Hit"
        let ChargeHolySound = asset<Sound> PackageName "ChargeHoly"
        let ChargeDimensionSound = asset<Sound> PackageName "ChargeDimension"
        let SlashSound = asset<Sound> PackageName "Slash"
        let TwisterSound = asset<Sound> PackageName "Twister"
        let IceSound = asset<Sound> PackageName "Ice"
        let SnowballSound = asset<Sound> PackageName "Snowball"
        let FireSound = asset<Sound> PackageName "Fire"
        let FlameSound = asset<Sound> PackageName "Flame"
        let InfernoSound = asset<Sound> PackageName "Inferno"
        let ThunderSound = asset<Sound> PackageName "Thunder"
        let ExplosionSound = asset<Sound> PackageName "Explosion"
        let ReadySound = asset<Sound> PackageName "Ready"
        let BuffSound = asset<Sound> PackageName "Buff"
        let DebuffSound = asset<Sound> PackageName "Debuff"
        let FieldSong = { FadeInTime = 0L; FadeOutTime = Constants.Audio.FadeOutTimeDefault; StartTime = 0L; Volume = Constants.Audio.SongVolumeDefault; Song = asset<Song> PackageName "Field" }

    [<RequireQualifiedAccess>]
    module Battle =

        let PackageName = "Battle"
        let CancelImage = asset<Image> PackageName "Cancel"
        let CutImage = asset<Image> PackageName "Cut"
        let LightCutImage = asset<Image> PackageName "LightCut"
        let ImpactSplashAnimationSheet = asset<Image> PackageName "ImpactSplash"
        let CycloneBlurAnimationSheet = asset<Image> PackageName "CycloneBlur"
        let SpikeAnimationSheet = asset<Image> PackageName "Spike"
        let CriticalAnimationSheet = asset<Image> PackageName "Critical"
        let HeavyCriticalAnimationSheet = asset<Image> PackageName "HeavyCritical"
        let CriticalSlashAnimationSheet = asset<Image> PackageName "CriticalSlash"
        let PoisonCutAnimationSheet = asset<Image> PackageName "PoisonCut"
        let PowerCutAnimationSheet = asset<Image> PackageName "PowerCut"
        let DispelCutAnimationSheet = asset<Image> PackageName "DispelCut"
        let DoubleCutAnimationSheet = asset<Image> PackageName "DoubleCut"
        let BoltAnimationSheet = asset<Image> PackageName "Bolt"
        let ExplosionAnimationSheet = asset<Image> PackageName "Explosion"
        let AfflictionsAnimationSheet = asset<Image> PackageName "Afflictions"
        let ChargeOrbAnimationSheet = asset<Image> PackageName "ChargeOrb"
        let SilenceAnimationSheet = asset<Image> PackageName "Silence"
        let SleepAnimationSheet = asset<Image> PackageName "Sleep"
        let ConfuseAnimationSheet = asset<Image> PackageName "Confuse"
        let CandleAnimationSheet = asset<Image> PackageName "Candle"
        let StaticAnimationSheet = asset<Image> PackageName "Static"
        let FireAnimationSheet = asset<Image> PackageName "Fire"
        let BurnAnimationSheet = asset<Image> PackageName "Burn"
        let FlameAnimationSheet = asset<Image> PackageName "Flame"
        let IceImage = asset<Image> PackageName "Ice"
        let SnowballImage = asset<Image> PackageName "Snowball"
        let HolyCastAnimationSheet = asset<Image> PackageName "HolyCast"
        let FloorLightAnimationSheet = asset<Image> PackageName "FloorLight"
        let FloorBeamAnimationSheet = asset<Image> PackageName "FloorBeam"
        let SparkleAnimationSheet = asset<Image> PackageName "Sparkle"
        let ProtectSphereImage = asset<Image> PackageName "ProtectSphere"
        let PurifyAnimationSheet = asset<Image> PackageName "Purify"
        let SilkAnimationSheet = asset<Image> PackageName "Silk"
        let ElectronBlueImage = asset<Image> PackageName "ElectronBlue"
        let NonLocationBlueImage = asset<Image> PackageName "NonLocationBlue"
        let ElectronGreenImage = asset<Image> PackageName "ElectronGreen"
        let NonLocationGreenImage = asset<Image> PackageName "NonLocationGreen"
        let PowerBuffImage = asset<Image> PackageName "PowerBuff"
        let MagicBuffImage = asset<Image> PackageName "MagicBuff"
        let ShieldBuffImage = asset<Image> PackageName "ShieldBuff"
        let TimeBuffImage = asset<Image> PackageName "TimeBuff"
        let PowerDebuffImage = asset<Image> PackageName "PowerDebuff"
        let MagicDebuffImage = asset<Image> PackageName "MagicDebuff"
        let ShieldDebuffImage = asset<Image> PackageName "ShieldDebuff"
        let TimeDebuffImage = asset<Image> PackageName "TimeDebuff"
        let FireSpinAnimationSheet = asset<Image> PackageName "FireSpin"